CREATE TABLE member_table (
  user_id varchar(20) NOT NULL,
  user_password varchar(15) NOT NULL,
  user_name nvarchar(10) NOT NULL,
  user_regdate datetime 
  PRIMARY KEY (user_id)
)

CREATE TABLE  (
  user_id varchar(20) NOT NULL,
  user_password varchar(15) NOT NULL,
  user_name nvarchar(10) NOT NULL,
  user_regdate datetime 
  PRIMARY KEY (user_id)
)

insert into board values('test', 'test', '테스터','Minim duis sit dolor cillum officia consectetur.', 'Non ullamco ad sunt irure consequat aliquip consequat nulla.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Voluptate dolore quis occaecat pariatur culpa commodo minim elit nisi dolore qui reprehenderit do.', 'Duis eu minim voluptate commodo aute.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Nulla mollit officia minim velit enim.', 'Anim aute aute ut nisi ex.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Amet aliqua labore aliqua quis non id non velit ut qui.', 'Sit irure cillum qui eiusmod dolor pariatur in magna magna exercitation.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Velit ad cupidatat mollit consequat amet quis ad veniam dolor reprehenderit cupidatat nostrud eiusmod occaecat.', 'Culpa quis irure irure do enim reprehenderit.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Adipisicing Lorem voluptate culpa pariatur mollit non reprehenderit in pariatur labore incididunt ipsum excepteur.', 'Dolor id Lorem fugiat cupidatat laboris pariatur qui fugiat eu id dolore ut.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Est dolore fugiat id reprehenderit consectetur ea consequat enim officia.', 'Esse labore anim dolore occaecat enim.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Ipsum dolor nisi culpa enim incididunt elit nostrud adipisicing.', 'Minim tempor id ea veniam tempor nostrud cillum aliquip mollit voluptate.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Eiusmod laboris quis minim quis cillum quis.', 'Quis sit laborum dolor elit aliqua id enim aute laborum Lorem nisi aliqua.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Commodo cupidatat duis deserunt fugiat.', 'Excepteur nostrud cupidatat exercitation ut ea non Lorem elit nisi ullamco.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Magna excepteur mollit id culpa culpa enim tempor cupidatat labore deserunt.', 'Culpa proident ad aliquip quis do voluptate.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Laboris esse adipisicing duis sit veniam exercitation aliqua exercitation.', 'Velit aliqua fugiat elit ullamco ad.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Fugiat excepteur pariatur et ea fugiat cupidatat nulla deserunt eu.', 'Tempor consequat do consectetur do quis quis ea est incididunt est proident qui eiusmod deserunt.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Labore duis duis aute nostrud adipisicing nostrud.', 'Ad exercitation sint quis quis reprehenderit ex ex voluptate proident dolor mollit consequat.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Ullamco elit excepteur amet elit eu voluptate id nulla irure aliquip aliquip eiusmod reprehenderit.', 'Quis aute culpa ea cillum amet quis excepteur tempor irure commodo quis consectetur.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Tempor nisi nulla mollit esse.', 'Est ea velit ea quis tempor cillum labore culpa deserunt tempor eu minim laborum excepteur.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Duis fugiat duis Lorem eu exercitation duis cupidatat excepteur minim ut est ipsum.', 'Quis cillum est voluptate id fugiat exercitation est duis non eiusmod sit anim ex.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Ipsum aliquip ipsum nostrud magna cillum.', 'Pariatur minim excepteur ipsum enim amet ad culpa.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Commodo aute mollit aliquip dolore eu excepteur irure ea adipisicing non officia ex mollit.', 'Nostrud reprehenderit anim dolor anim non enim laborum excepteur anim fugiat aliqua pariatur.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Culpa aute sunt Lorem amet nostrud sint fugiat dolore mollit esse eu mollit.', 'Laborum id incididunt ipsum proident minim ipsum Lorem nisi consectetur eu dolor.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Commodo ullamco fugiat sunt eu pariatur exercitation do deserunt.', 'Veniam laboris tempor nostrud nulla sint nisi do consectetur ad.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Dolor aliquip quis velit sint elit ex duis elit.', 'Ad irure nostrud labore excepteur fugiat consectetur sit.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Aute labore minim id non adipisicing incididunt consequat id fugiat ullamco sunt.', 'Lorem tempor sit esse eu officia aliquip do aute officia aliquip duis elit.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Duis in ad adipisicing culpa.', 'Elit proident nostrud Lorem laborum aliquip cillum aute ea non deserunt.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Sint ullamco pariatur non nulla laboris aliquip ad anim aliquip et amet do et excepteur.', 'Ea ea Lorem laborum ipsum anim dolor fugiat.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Nisi esse nostrud elit cillum nulla irure id sint cupidatat qui.', 'Consectetur dolore amet ad minim Lorem eiusmod et qui ad dolore.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','In proident sint sit cupidatat aliqua minim voluptate velit commodo labore dolore id cupidatat aute.', 'Ipsum et ea est ex veniam eu Lorem ipsum deserunt eiusmod culpa deserunt velit.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Culpa ullamco eiusmod aliquip eiusmod minim minim non.', 'Veniam eiusmod quis ipsum esse irure aliqua pariatur.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Laborum minim qui est in dolor officia deserunt.', 'Est in ad incididunt voluptate cillum et tempor voluptate ipsum est est ullamco.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Proident est nostrud laborum et voluptate pariatur sint ad amet adipisicing eiusmod ad.', 'Fugiat aliquip dolore duis sit est Lorem exercitation consectetur consectetur amet id.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','In est laborum consectetur pariatur deserunt consectetur et pariatur tempor culpa.', 'Labore duis culpa duis eiusmod.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Laboris quis ipsum quis aliqua magna enim amet enim.', 'Culpa et sit pariatur dolor eiusmod in.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Aliquip eu fugiat aute nulla reprehenderit quis proident nisi deserunt culpa dolor in.', 'Cillum pariatur irure ut excepteur eu do quis ex sunt culpa excepteur tempor.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Consectetur magna ut exercitation exercitation velit cillum adipisicing laborum.', 'Qui incididunt non nulla occaecat fugiat do irure aliquip qui ullamco eiusmod.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Nostrud velit duis id sit eiusmod occaecat aliquip cillum labore.', 'Enim ea reprehenderit adipisicing reprehenderit nulla cupidatat anim id cupidatat mollit nisi.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Aute tempor dolore deserunt velit in nostrud minim.', 'Elit est consectetur et Lorem do veniam magna nisi sit irure cupidatat aute quis.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Culpa reprehenderit aliqua aliqua irure eiusmod esse ad labore.', 'Consequat adipisicing officia duis ipsum aliquip sunt non mollit ad.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Qui id laborum Lorem nisi et aliquip anim aute culpa labore culpa do labore duis.', 'Velit deserunt reprehenderit esse quis fugiat.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Cillum irure aliqua nostrud exercitation ipsum Lorem aliqua enim eu aute.', 'Ea duis proident magna et.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Est officia non consectetur anim velit do tempor non do commodo sit et culpa irure.', 'Enim aliquip ea elit esse.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Non qui elit et minim veniam id ipsum.', 'Cillum est anim consequat adipisicing consequat ex ex.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Aliquip excepteur ipsum ea exercitation commodo elit eiusmod officia laboris nulla nisi incididunt est.', 'Veniam deserunt cillum qui anim culpa sint sit ea quis.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Ut sit exercitation aliquip nisi consectetur elit magna esse.', 'Esse eiusmod nostrud id do tempor laborum ullamco ut amet sunt laborum.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Qui amet et qui mollit sit dolor id adipisicing adipisicing.', 'Laborum do aliqua deserunt magna officia in laborum ut magna id sint consequat cillum pariatur.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Dolore et est sint in duis eiusmod mollit ut veniam veniam culpa.', 'Lorem labore fugiat ipsum irure pariatur velit exercitation ad magna.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Sint cupidatat elit consectetur veniam magna proident do nulla aute commodo mollit occaecat elit.', 'Ad mollit cillum esse labore ut occaecat exercitation tempor.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Nulla laborum est velit cupidatat officia officia esse voluptate commodo labore occaecat.', 'Proident duis nulla ullamco irure amet est duis cillum ut anim esse aliquip sunt in.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','In labore ipsum irure nisi incididunt veniam qui est est magna incididunt consectetur eu commodo.', 'Ea amet cillum sint non esse sint deserunt exercitation incididunt voluptate eiusmod laborum veniam sit.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Aute adipisicing ullamco exercitation eu excepteur eiusmod.', 'Dolor adipisicing irure deserunt et magna veniam mollit aliquip officia ut.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Commodo ea do exercitation officia incididunt dolore nostrud.', 'Officia ad irure eiusmod laborum mollit aliqua labore voluptate reprehenderit ex velit deserunt officia.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Enim culpa incididunt nulla labore qui ut dolore minim occaecat dolor ex proident.', 'Cupidatat enim commodo aliqua nostrud duis anim sunt nulla cillum dolor ipsum.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Pariatur aute eiusmod in sit dolor consequat.', 'Eu sunt consequat cillum tempor est eu qui cupidatat dolor laborum.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Est voluptate excepteur tempor voluptate id ullamco et laboris nisi dolor exercitation id excepteur.', 'Ea ullamco commodo laboris ipsum.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Qui ea do fugiat incididunt esse magna excepteur.', 'Non cillum esse id aliqua nisi culpa dolore eu Lorem aliquip minim consectetur esse do.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Tempor adipisicing et elit amet culpa commodo dolor mollit Lorem aute ullamco cillum.', 'Cupidatat cillum ut eu amet dolor.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Laborum sit tempor commodo excepteur nulla tempor eiusmod nisi.', 'Quis amet ad est aliqua.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Aliquip elit exercitation ex cillum Lorem id magna culpa consectetur elit.', 'Quis est elit aliquip cupidatat dolor Lorem veniam nisi non minim et consectetur non nisi.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Anim est occaecat dolore voluptate ex.', 'Irure adipisicing occaecat qui occaecat.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Exercitation ea fugiat deserunt adipisicing non deserunt non reprehenderit dolore sint ullamco exercitation exercitation sunt.', 'Mollit amet cillum officia ullamco nostrud cupidatat ex quis anim id eu.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Aliqua nulla amet adipisicing aliqua nisi enim duis irure exercitation consequat ex labore.', 'Nostrud ut enim cupidatat anim laborum pariatur sint incididunt laborum et amet.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Ullamco exercitation exercitation commodo ut nisi sunt enim aute nostrud officia amet exercitation laboris.', 'Cillum amet deserunt nisi aliquip irure sit labore dolor officia pariatur ipsum.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Labore duis fugiat cupidatat dolor consectetur.', 'Ea nulla eu aliquip ad ullamco ullamco magna.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Fugiat incididunt minim magna sit.', 'Culpa proident culpa aute ipsum consectetur do ea aliqua.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Tempor mollit eu fugiat mollit in amet aliquip consectetur nisi.', 'Qui cillum sunt anim dolor occaecat ex fugiat dolore.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Irure magna laborum excepteur ullamco excepteur veniam pariatur veniam non ex ad et consequat.', 'Elit fugiat cupidatat pariatur irure veniam consectetur ullamco duis ipsum irure ut aute proident enim.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Laborum nisi in sunt eu minim.', 'Nisi ut cupidatat voluptate reprehenderit consectetur eu officia eiusmod et minim reprehenderit ex qui quis.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Nulla ex eiusmod anim non qui cupidatat dolore adipisicing officia do aliquip dolore.', 'Fugiat irure amet labore cupidatat do.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Fugiat exercitation eiusmod consequat in dolor.', 'Irure officia occaecat fugiat sint tempor est ad ullamco sint labore.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Velit in duis quis sit.', 'Adipisicing ea anim ipsum dolor fugiat duis sit ullamco magna non culpa mollit proident.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Ipsum amet duis excepteur reprehenderit culpa reprehenderit eiusmod velit.', 'Ipsum duis dolor amet dolore magna cillum et enim.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Magna nulla sint Lorem ad.', 'Anim esse nulla qui ipsum cupidatat anim.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Irure ullamco et qui eu nisi deserunt.', 'Incididunt enim fugiat cupidatat cillum est reprehenderit aliquip.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Nulla voluptate exercitation laboris qui aliquip ut.', 'Cillum dolor sunt ullamco minim.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Cillum magna officia dolore ut ea ex ut non sunt voluptate mollit laborum.', 'Lorem consequat eiusmod ut deserunt aliquip ex elit cillum Lorem laboris.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Tempor elit eiusmod irure excepteur cillum.', 'Id anim aute enim aliquip consectetur quis in magna ut velit exercitation nulla proident.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Sunt labore nostrud tempor labore anim magna incididunt nostrud aliqua voluptate exercitation anim quis.', 'Do ad est elit velit labore quis esse.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Id velit ad non ex anim et ad minim enim eu do ut consequat.', 'Magna sint aliqua incididunt aute non quis duis aute dolor incididunt officia incididunt aliquip.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Esse nostrud laboris cillum adipisicing velit velit anim non.', 'Aliqua anim mollit ullamco est labore mollit dolor mollit nulla ad sit consectetur minim irure.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Qui officia excepteur veniam culpa.', 'Aute Lorem irure commodo consectetur anim quis adipisicing consectetur proident.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Ipsum incididunt ex fugiat minim dolor duis nulla enim occaecat.', 'Sit velit dolor aute nulla.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Eiusmod dolore duis ut excepteur deserunt Lorem culpa fugiat dolore aliquip.', 'Fugiat enim ullamco quis aliquip sit reprehenderit commodo sunt proident labore aute eu qui.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Deserunt nisi culpa incididunt in deserunt occaecat et cupidatat laboris do.', 'Aute ullamco nulla Lorem fugiat id culpa id laborum.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Officia consequat ipsum commodo esse mollit adipisicing.', 'Aute excepteur sit aute id qui est culpa do ipsum dolore eiusmod.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Consequat culpa reprehenderit aute nulla nulla fugiat nulla reprehenderit.', 'Tempor officia tempor adipisicing elit sit deserunt commodo sit.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Culpa consequat mollit elit pariatur quis laborum tempor enim aute in excepteur nisi ad.', 'Tempor est exercitation ullamco tempor et do duis cillum duis mollit eiusmod.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Consectetur sint quis esse enim dolore magna ex irure pariatur tempor.', 'Mollit nostrud ea consectetur commodo.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Consectetur sit mollit aliquip exercitation id labore aute eiusmod aliquip commodo excepteur veniam.', 'Id do non velit nisi nostrud voluptate.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Incididunt nostrud pariatur reprehenderit officia nisi officia et.', 'Officia voluptate cillum velit commodo anim est sit sit pariatur Lorem voluptate pariatur anim.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Commodo dolor esse consectetur officia ipsum commodo dolor consequat velit excepteur.', 'Officia incididunt voluptate mollit fugiat deserunt sunt.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Quis do laborum cupidatat cillum pariatur culpa esse nulla ut.', 'Amet sit cupidatat ad Lorem ipsum elit proident id proident.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Eu tempor enim voluptate magna adipisicing incididunt anim pariatur ad proident velit.', 'Occaecat mollit fugiat ipsum ipsum ad pariatur ut pariatur.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Incididunt adipisicing consectetur velit elit ullamco cupidatat cillum Lorem labore ullamco ipsum.', 'Cupidatat cillum aliqua minim pariatur eiusmod consectetur excepteur aliquip dolore aliqua qui.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Officia sint excepteur et consectetur do.', 'Irure culpa nisi excepteur eu dolor ullamco aliquip.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Cillum in laborum eiusmod consectetur in do reprehenderit nulla.', 'Sint aliquip ad sunt elit labore sint.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Aliquip exercitation magna cillum commodo magna eu sit.', 'Sunt laborum dolor dolor id occaecat id sint do minim.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Adipisicing irure esse excepteur veniam nostrud officia.', 'Exercitation laborum et eiusmod exercitation.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Quis excepteur veniam non irure eu fugiat Lorem adipisicing est occaecat.', 'Fugiat ad consequat quis dolore duis voluptate et.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Dolore velit irure culpa est officia ea nostrud labore culpa aliquip.', 'Consequat do aliqua quis consectetur aliquip mollit.', '', getdate(), 0, 0)
insert into board values('test', 'test', '테스터','Commodo duis irure duis amet consectetur aliqua nisi do aute incididunt occaecat sit aute.', 'Ex eiusmod irure ut voluptate deserunt Lorem magna culpa exercitation excepteur.', '', getdate(), 0, 0)